name: next_buy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path: ^1.8.3
  intl: ^0.19.0
  fluttertoast: ^8.2.5
  flutter_social_button: ^1.1.4+1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5
  get: ^4.6.6
  flutter_native_splash: ^2.4.0
  carousel_slider: ^4.2.1
  firebase_storage: ^11.7.5

  google_fonts: ^6.2.1
  http: ^1.2.1
  cached_network_image: ^3.4.0
  flutter_cache_manager: ^3.4.1
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.2.3
  rxdart: ^0.28.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/menu.png
    - assets/images/onboding1.png
    - assets/images/onboding2.png
    - assets/images/onboding.png
    - assets/images/cart.png
    - assets/images/menu.png
    - assets/images/downloud.gif
    - assets/images/appstore.png
    - assets/images/playstore.png
    - assets/images/heart.png
    - assets/images/add-to-basket.png
    - assets/images/setting.png
    - assets/images/drayer.png
    - assets/images/1cart.png
    - assets/images/sale.png
    - assets/images/Borcelle.png
    - assets/images/onboding1.png
    - assets/images/on1.png
    - assets/images/z.png
    - assets/images/google.png
    - assets/images/bed.png
    - assets/images/a.png
    - assets/images/b.png
    - assets/images/c.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/1.png
    - assets/images/p.png
    - assets/images/p2.png
    - assets/images/p3.png
    - assets/images/p4.png
    - assets/images/p5.png
    - assets/images/p6.png
    - assets/images/p7.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/14.png
    - assets/images/15.png
    - assets/images/17.png
flutter_native_splash:
  color: "#81ef59"
  image: assets/images/Borcelle.png
  android: true
  ios: true
  web: true
